;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 16/11/2022 8:44:15 am
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0004	$	_main:
;proj6.pbas,3 :: 		main:
$0004	$	_main_main:
;proj6.pbas,4 :: 		trisb=0
$0004	$1303			BCF	STATUS, RP1
$0005	$1683			BSF	STATUS, RP0
$0006	$0186			CLRF	TRISB, 1
;proj6.pbas,5 :: 		portb=1
$0007	$3001			MOVLW	1
$0008	$1283			BCF	STATUS, RP0
$0009	$0086			MOVWF	PORTB
$000A	$	proj6_L_0:
$000A	$280A			GOTO	$
