;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 11/17/2022 11:31:52 AM
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0004	$	_main:
;midterm.pbas,3 :: 		main:
$0004	$	_main_main:
;midterm.pbas,4 :: 		trisb=0
$0004	$1303			BCF	STATUS, RP1
$0005	$1683			BSF	STATUS, RP0
$0006	$1303			BCF	STATUS, RP1
$0007	$1683			BSF	STATUS, RP0
$0008	$0186			CLRF	TRISB, 1
;midterm.pbas,5 :: 		portb=0
$0009	$1283			BCF	STATUS, RP0
$000A	$0186			CLRF	PORTB, 1
;midterm.pbas,6 :: 		trisa=0
$000B	$1683			BSF	STATUS, RP0
$000C	$0185			CLRF	TRISA, 1
;midterm.pbas,7 :: 		porta=0
$000D	$1283			BCF	STATUS, RP0
$000E	$0185			CLRF	PORTA, 1
;midterm.pbas,9 :: 		main2:
$000F	$	_main_main2:
;midterm.pbas,10 :: 		if porta.0=1 then
$000F	$3001			MOVLW	1
$0010	$0505			ANDWF	PORTA, 0
$0011	$00C1			MOVWF	STACK_1
$0012	$0841			MOVF	STACK_1, 0
$0013	$3A01			XORLW	1
$0014	$1D03			BTFSS	STATUS, Z
$0015	$2819			GOTO	midterm_L_2
$0016	$	midterm_L_1:
;midterm.pbas,11 :: 		portb.1=2
$0016	$	midterm_L_4:
$0016	$1486			BSF	PORTB, 1
$0017	$	midterm_L_5:
;midterm.pbas,12 :: 		portb=%0000001
$0017	$3001			MOVLW	1
$0018	$0086			MOVWF	PORTB
$0019	$	midterm_L_2:
;midterm.pbas,13 :: 		end if
$0019	$	midterm_L_3:
;midterm.pbas,14 :: 		if porta.1=1 then
$0019	$3000			MOVLW	0
$001A	$1885			BTFSC	PORTA, 1
$001B	$3001			MOVLW	1
$001C	$00C1			MOVWF	STACK_1
$001D	$0841			MOVF	STACK_1, 0
$001E	$3A01			XORLW	1
$001F	$1D03			BTFSS	STATUS, Z
$0020	$2822			GOTO	midterm_L_7
$0021	$	midterm_L_6:
;midterm.pbas,15 :: 		portb.0=1
$0021	$	midterm_L_9:
$0021	$1406			BSF	PORTB, 0
$0022	$	midterm_L_10:
$0022	$	midterm_L_7:
;midterm.pbas,16 :: 		end if
$0022	$	midterm_L_8:
;midterm.pbas,17 :: 		goto main
$0022	$2804			GOTO	_main_main
$0023	$2823			GOTO	$
