;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 11/24/2022 11:03:20 AM
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$284F			GOTO	_main
$0004	$	_mask:
;p11.pbas,4 :: 		sub function mask(dim num as byte)as byte
;p11.pbas,6 :: 		case 0 result = $C0
$0004	$	p11_L_3:
$0004	$1303			BCF	STATUS, RP1
$0005	$1283			BCF	STATUS, RP0
$0006	$080D			MOVF	FARG_mask, 0
$0007	$3A00			XORLW	0
$0008	$1D03			BTFSS	STATUS, Z
$0009	$280D			GOTO	p11_L_4
$000A	$	p11_L_2:
$000A	$30C0			MOVLW	192
$000B	$008E			MOVWF	_mask_local_result
$000C	$284C			GOTO	p11_L_1
$000D	$	p11_L_4:
;p11.pbas,7 :: 		case 1 result = $F9
$000D	$	p11_L_6:
$000D	$080D			MOVF	FARG_mask, 0
$000E	$3A01			XORLW	1
$000F	$1D03			BTFSS	STATUS, Z
$0010	$2814			GOTO	p11_L_7
$0011	$	p11_L_5:
$0011	$30F9			MOVLW	249
$0012	$008E			MOVWF	_mask_local_result
$0013	$284C			GOTO	p11_L_1
$0014	$	p11_L_7:
;p11.pbas,8 :: 		case 2 result = $A4
$0014	$	p11_L_9:
$0014	$080D			MOVF	FARG_mask, 0
$0015	$3A02			XORLW	2
$0016	$1D03			BTFSS	STATUS, Z
$0017	$281B			GOTO	p11_L_10
$0018	$	p11_L_8:
$0018	$30A4			MOVLW	164
$0019	$008E			MOVWF	_mask_local_result
$001A	$284C			GOTO	p11_L_1
$001B	$	p11_L_10:
;p11.pbas,9 :: 		case 3 result = $B0
$001B	$	p11_L_12:
$001B	$080D			MOVF	FARG_mask, 0
$001C	$3A03			XORLW	3
$001D	$1D03			BTFSS	STATUS, Z
$001E	$2822			GOTO	p11_L_13
$001F	$	p11_L_11:
$001F	$30B0			MOVLW	176
$0020	$008E			MOVWF	_mask_local_result
$0021	$284C			GOTO	p11_L_1
$0022	$	p11_L_13:
;p11.pbas,10 :: 		case 4 result = $99
$0022	$	p11_L_15:
$0022	$080D			MOVF	FARG_mask, 0
$0023	$3A04			XORLW	4
$0024	$1D03			BTFSS	STATUS, Z
$0025	$2829			GOTO	p11_L_16
$0026	$	p11_L_14:
$0026	$3099			MOVLW	153
$0027	$008E			MOVWF	_mask_local_result
$0028	$284C			GOTO	p11_L_1
$0029	$	p11_L_16:
;p11.pbas,11 :: 		case 5 result = $92
$0029	$	p11_L_18:
$0029	$080D			MOVF	FARG_mask, 0
$002A	$3A05			XORLW	5
$002B	$1D03			BTFSS	STATUS, Z
$002C	$2830			GOTO	p11_L_19
$002D	$	p11_L_17:
$002D	$3092			MOVLW	146
$002E	$008E			MOVWF	_mask_local_result
$002F	$284C			GOTO	p11_L_1
$0030	$	p11_L_19:
;p11.pbas,12 :: 		case 6 result = $82
$0030	$	p11_L_21:
$0030	$080D			MOVF	FARG_mask, 0
$0031	$3A06			XORLW	6
$0032	$1D03			BTFSS	STATUS, Z
$0033	$2837			GOTO	p11_L_22
$0034	$	p11_L_20:
$0034	$3082			MOVLW	130
$0035	$008E			MOVWF	_mask_local_result
$0036	$284C			GOTO	p11_L_1
$0037	$	p11_L_22:
;p11.pbas,13 :: 		case 7 result = $F8
$0037	$	p11_L_24:
$0037	$080D			MOVF	FARG_mask, 0
$0038	$3A07			XORLW	7
$0039	$1D03			BTFSS	STATUS, Z
$003A	$283E			GOTO	p11_L_25
$003B	$	p11_L_23:
$003B	$30F8			MOVLW	248
$003C	$008E			MOVWF	_mask_local_result
$003D	$284C			GOTO	p11_L_1
$003E	$	p11_L_25:
;p11.pbas,14 :: 		case 8 result = $80
$003E	$	p11_L_27:
$003E	$080D			MOVF	FARG_mask, 0
$003F	$3A08			XORLW	8
$0040	$1D03			BTFSS	STATUS, Z
$0041	$2845			GOTO	p11_L_28
$0042	$	p11_L_26:
$0042	$3080			MOVLW	128
$0043	$008E			MOVWF	_mask_local_result
$0044	$284C			GOTO	p11_L_1
$0045	$	p11_L_28:
;p11.pbas,15 :: 		case 9 result = $90
$0045	$	p11_L_30:
$0045	$080D			MOVF	FARG_mask, 0
$0046	$3A09			XORLW	9
$0047	$1D03			BTFSS	STATUS, Z
$0048	$284C			GOTO	p11_L_31
$0049	$	p11_L_29:
$0049	$3090			MOVLW	144
$004A	$008E			MOVWF	_mask_local_result
$004B	$284C			GOTO	p11_L_1
$004C	$	p11_L_31:
$004C	$	p11_L_1:
;p11.pbas,16 :: 		end select
$004C	$	p11_L_0:
$004C	$080E			MOVF	_mask_local_result, 0
$004D	$00C0			MOVWF	STACK_0
$004E	$0008			RETURN
$004F	$	_main:
;p11.pbas,18 :: 		main:
$004F	$	_main_main:
;p11.pbas,19 :: 		trisa=0
$004F	$1303			BCF	STATUS, RP1
$0050	$1683			BSF	STATUS, RP0
$0051	$0185			CLRF	TRISA, 1
;p11.pbas,20 :: 		trisb=0
$0052	$0186			CLRF	TRISB, 1
;p11.pbas,21 :: 		porta=0
$0053	$1283			BCF	STATUS, RP0
$0054	$0185			CLRF	PORTA, 1
;p11.pbas,22 :: 		portb=mask(0)
$0055	$018D			CLRF	FARG_mask, 1
$0056	$2004			CALL	_mask
$0057	$0840			MOVF	STACK_0, 0
$0058	$0086			MOVWF	PORTB
;p11.pbas,23 :: 		x=0
$0059	$018C			CLRF	_x, 1
;p11.pbas,25 :: 		main2:
$005A	$	_main_main2:
;p11.pbas,26 :: 		if porta.0=1 then
$005A	$3001			MOVLW	1
$005B	$0505			ANDWF	PORTA, 0
$005C	$00C1			MOVWF	STACK_1
$005D	$0841			MOVF	STACK_1, 0
$005E	$3A01			XORLW	1
$005F	$1D03			BTFSS	STATUS, Z
$0060	$288F			GOTO	p11_L_34
$0061	$	p11_L_33:
;p11.pbas,27 :: 		x=x+1
$0061	$0A0C			INCF	_x, 0
$0062	$00C0			MOVWF	STACK_0
$0063	$0840			MOVF	STACK_0, 0
$0064	$008C			MOVWF	_x
;p11.pbas,28 :: 		portb=mask(x)
$0065	$0840			MOVF	STACK_0, 0
$0066	$008D			MOVWF	FARG_mask
$0067	$2004			CALL	_mask
$0068	$0840			MOVF	STACK_0, 0
$0069	$0086			MOVWF	PORTB
;p11.pbas,29 :: 		delay_ms(100)
$006A	$3002			MOVLW	2
$006B	$00CC			MOVWF	STACK_12
$006C	$30FF			MOVLW	255
$006D	$00CB			MOVWF	STACK_11
$006E	$30FF			MOVLW	255
$006F	$00CA			MOVWF	STACK_10
$0070	$0BCC			DECFSZ	STACK_12, F
$0071	$2873			GOTO	$+2
$0072	$287A			GOTO	$+8
$0073	$0BCB			DECFSZ	STACK_11, F
$0074	$2876			GOTO	$+2
$0075	$2879			GOTO	$+4
$0076	$0BCA			DECFSZ	STACK_10, F
$0077	$2876			GOTO	$-1
$0078	$2873			GOTO	$-5
$0079	$2870			GOTO	$-9
$007A	$3006			MOVLW	6
$007B	$00CB			MOVWF	STACK_11
$007C	$30FF			MOVLW	255
$007D	$00CA			MOVWF	STACK_10
$007E	$0BCB			DECFSZ	STACK_11, F
$007F	$2881			GOTO	$+2
$0080	$2884			GOTO	$+4
$0081	$0BCA			DECFSZ	STACK_10, F
$0082	$2881			GOTO	$-1
$0083	$287E			GOTO	$-5
$0084	$300A			MOVLW	10
$0085	$00CA			MOVWF	STACK_10
$0086	$0BCA			DECFSZ	STACK_10, F
$0087	$2886			GOTO	$-1
$0088	$0000			NOP
;p11.pbas,30 :: 		if x>9 then
$0089	$080C			MOVF	_x, 0
$008A	$3C09			SUBLW	9
$008B	$1803			BTFSC	STATUS, C
$008C	$288F			GOTO	p11_L_37
$008D	$	p11_L_36:
;p11.pbas,31 :: 		x=9
$008D	$3009			MOVLW	9
$008E	$008C			MOVWF	_x
$008F	$	p11_L_37:
;p11.pbas,32 :: 		end if
$008F	$	p11_L_38:
$008F	$	p11_L_34:
;p11.pbas,33 :: 		end if
$008F	$	p11_L_35:
;p11.pbas,34 :: 		goto main2
$008F	$285A			GOTO	_main_main2
$0090	$2890			GOTO	$
